FROM python:3.9

RUN python -m pip install --no-cache-dir --upgrade pip

RUN pip install --no-cache-dir boto3==1.26.4 awswrangler==2.18
FROM nodered/node-red:latest
USER root
RUN ln -sf python3 /usr/bin/python
USER node-red
