FROM nodered/node-red:latest
USER root
FROM python:3.7.3-alpine

# Install pip for Python 3.7
RUN wget https://bootstrap.pypa.io/get-pip.py && \
    python3.7 get-pip.py && \
    rm get-pip.py

RUN apk add --update --no-cache \
    build-base \
    python3-dev \
    && pip install --no-cache-dir \
    numpy==1.21.5 \
    pandas==1.3.5 \
    awswrangler==2.11.0 \
    && rm -rf /root/.cache/pip/*

USER node-red
